# The Gibbs energy for the 10 steps of the glycolysis

# Glycolysis kinetic parameters 

[deltaG]
step1  = -20.4   # 葡萄糖磷酸化 (己糖激酶)
step2  = 2.6    # 6-磷酸葡萄糖异构化 (磷酸己糖异构酶)
step3  = -17.8     # 6-磷酸果糖磷酸化 (磷酸果糖激酶-1)
step4  = 6   # 1,6-二磷酸果糖裂解 (醛缩酶)
step5  = 5.6     # 磷酸二羟丙酮异构化 (丙糖磷酸异构酶)
step6  = 18.3     # 3-磷酸甘油醛氧化 (3-磷酸甘油醛脱氢酶)
step7  = -19.5    # 1,3-二磷酸甘油酸底物水平磷酸化 (磷酸甘油酸激酶)
step8  = 4.5   # 3-磷酸甘油酸变位 (磷酸甘油酸变位酶)
step9  = -3.8    # 2-磷酸甘油酸脱水 (烯醇化酶)
step10 = -25.0   # 磷酸烯醇式丙酮酸底物水平磷酸化 (丙酮酸激酶)

[k1]
kf = 100.0   # glucose phosphorylation (forward)
kr = 0.1     # glucose phosphorylation (reverse)

[k2]
kf = 50.0    # hexokinase (forward)
kr = 50.0    # hexokinase (reverse)

[k3]
kf = 80.0    # fructokinase (forward)
kr = 0.01    # fructokinase (reverse)

[k4]
kf = 20.0    # fructose-1,6-bisphosphatase (forward)
kr = 0.1     # fructose-1,6-bisphosphatase (reverse)

[k5]
kf = 200.0   # phosphoenolpyruvate isomerase (forward)
kr = 200.0   # phosphoenolpyruvate isomerase (reverse)

[k6]
kf = 150.0   # dihydroxyacetone phosphate oxidase (forward)
kr = 0.1     # dihydroxyacetone phosphate oxidase (reverse)

[k7]
kf = 300.0   # phosphoglycerate kinase (forward)
kr = 0.1     # phosphoglycerate kinase (reverse)

[k8]
kf = 100.0   # phosphoglycerate mutase (forward)
kr = 100.0   # phosphoglycerate mutase (reverse)

[k9]
kf = 50.0    # enolase (forward)
kr = 0.1     # enolase (reverse)

[k10]
kf = 200.0   # pyruvate kinase (forward)
kr = 0.01    # pyruvate kinase (reverse)

[initial_conditions]
Glucose  = 5.0      # mM
G6P      = 0.0
F6P      = 0.0
F16BP    = 0.0
DHAP     = 0.0
GAP      = 0.0
BPG13    = 0.0
PG3      = 0.0
PG2      = 0.0
PEP      = 0.0
Pyruvate = 0.0
ATP      = 3.0      # mM
ADP      = 0.5
NAD      = 0.9      # mM
NADH     = 0.1
Pi       = 10.0     # mM
H2O      = 55.5     # mM (水的浓度)
H        = 1e-7     # mM (pH 7)

[supply]
# 单位：mM/s，常量供给/移除通量（可继续调优）
atp_in   = 0.00   # ∅ -> ATP
atp_out  = 0.05   # ATP -> ∅
adp_in   = 0.10   # ∅ -> ADP
adp_out  = 0.00   # ADP -> ∅
nad_in   = 0.10   # ∅ -> NAD+
nadh_out = 0.15   # NADH -> ∅
pi_in    = 0.15   # ∅ -> Pi
h_out    = 0.10   # H -> ∅
