step4 = "✅ 强烈放能反应 (ΔG = -28.25 kJ/mol)"
step8 = "⚠️ 接近平衡 (ΔG = 4.49 kJ/mol)"
step2 = "✅ 强烈放能反应 (ΔG = -31.65 kJ/mol)"
step3 = "✅ 强烈放能反应 (ΔG = -52.05 kJ/mol)"
step1 = "✅ 强烈放能反应 (ΔG = -54.65 kJ/mol)"
step5 = "✅ 强烈放能反应 (ΔG = -28.65 kJ/mol)"
step9 = "⚠️ 接近平衡 (ΔG = 1.21 kJ/mol)"
step7 = "⚠️ 接近平衡 (ΔG = 4.88 kJ/mol)"
step10 = "✅ 放能反应 (ΔG = -0.46 kJ/mol)"
step6 = "⚠️ 接近平衡 (ΔG = 1.08 kJ/mol)"
